- name: uwsgi.ini
  template:
    src: uwsgi.ini.j2
    dest: "{{ openwisp2_path }}/uwsgi.ini"
  notify: reload supervisor

- name: supervisor uwsgi
  template:
    src: supervisor/openwisp2.j2
    dest: "{{ supervisor_path | format('openwisp2') }}"
  notify: reload supervisor

- name: supervisor daphne
  template:
    src: supervisor/daphne.j2
    dest: "{{ supervisor_path | format('daphne') }}"
  notify: reload supervisor

- name: supervisor celery
  template:
    src: celery.j2
    dest: "{{ supervisor_path | format('celery') }}"
  notify: reload supervisor
